{{- if .Values.services.redisInsight }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openexposure.fullname" . }}-redis-insight
  labels:
    app.kubernetes.io/name: redis-insight
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis-insight
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas.redisInsight | default .Values.replicas.default }}
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-insight
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-insight
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: redis-insight
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: redis-insight
          image: {{ .Values.images.redisInsight }}
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 5540
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /data
            - name: logs
              mountPath: /data/logs
      volumes:
        - name: data
          emptyDir: {}
        - name: logs
          emptyDir: {}
{{- end }}
