{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: grafana
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: helm
spec:
  replicas: {{ .Values.grafana.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: grafana
      {{- if and .Values.grafana.config (hasKey .Values.grafana.config "enabled") .Values.grafana.config.enabled }}
      annotations:
        checksum/config: {{ toYaml .Values.grafana.config | sha256sum | quote }}
      {{- end }}
    spec:
      containers:
        - name: grafana
          image: {{ .Values.grafana.image }}
          imagePullPolicy: {{ .Values.grafana.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.grafana.port }}
              name: http
          {{- if .Values.grafana.env }}
          env:
            {{- range .Values.grafana.env }}
            - name: {{ .name }}
              {{- if hasKey . "value" }}
              value: {{ .value | quote }}
              {{- else if hasKey . "valueFrom" }}
              valueFrom:
{{ toYaml .valueFrom | nindent 16 }}
              {{- else }}
              value: ""
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if and .Values.grafana.config (hasKey .Values.grafana.config "enabled") .Values.grafana.config.enabled }}
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards
            - name: storage
              mountPath: /var/lib/grafana
          {{- end }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.grafana.port }}
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.grafana.port }}
            initialDelaySeconds: 5
            timeoutSeconds: 5
      {{- if and .Values.grafana.config (hasKey .Values.grafana.config "enabled") .Values.grafana.config.enabled }}
      volumes:
        - name: datasources
          configMap:
            name: {{ .Release.Name }}-grafana-datasources
        - name: dashboards-config
          configMap:
            name: {{ .Release.Name }}-grafana-dashboards
        - name: storage
          emptyDir: {}
      {{- end }}
{{- end }}
