{{- if .Values.podDisruptionBudget.enabled }}
---
# Monitoring Event PodDisruptionBudget
{{- if .Values.monitoringEvent.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-monitoring-event
  labels:
    app.kubernetes.io/name: monitoring-event
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: helm
spec:
  minAvailable: {{ .Values.podDisruptionBudget.monitoringEvent.minAvailable | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: monitoring-event
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

---
# UE Identity PodDisruptionBudget
{{- if .Values.ueIdentity.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-ue-identity
  labels:
    app.kubernetes.io/name: ue-identity
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: helm
spec:
  minAvailable: {{ .Values.podDisruptionBudget.ueIdentity.minAvailable | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ue-identity
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

---
# Core Simulator PodDisruptionBudget
{{- if .Values.coreSimulator.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-core-simulator
  labels:
    app.kubernetes.io/name: core-simulator
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: helm
spec:
  minAvailable: {{ .Values.podDisruptionBudget.coreSimulator.minAvailable | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: core-simulator
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

---
# Redis PodDisruptionBudget
{{- if .Values.redis.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: helm
spec:
  minAvailable: {{ .Values.podDisruptionBudget.redis.minAvailable | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

---
# Prometheus PodDisruptionBudget
{{- if .Values.prometheus.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: helm
spec:
  minAvailable: {{ .Values.podDisruptionBudget.prometheus.minAvailable | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

---
# Grafana PodDisruptionBudget
{{- if .Values.grafana.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: helm
spec:
  minAvailable: {{ .Values.podDisruptionBudget.grafana.minAvailable | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}
