{{- if .Values.redis.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nef-redis-secret
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: helm
type: Opaque
data:
  # Generate a secure random password for Redis
  # Use: kubectl create secret generic nef-redis-secret --from-literal=redis-password=$(openssl rand -base64 32)
  # Or update this value with: echo -n 'your-secure-password' | base64
  redis-password: {{ .Values.redis.auth.password | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}
---
{{- if .Values.capif.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: nef-capif-secret
  labels:
    app.kubernetes.io/name: capif
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: capif
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: helm
type: Opaque
data:
  # CAPIF service credentials
  # Update these values with actual credentials encoded in base64
  # Use: echo -n 'username' | base64
  capif-username: {{ .Values.capif.auth.username | default "nef-semproj" | b64enc | quote }}
  capif-password: {{ .Values.capif.auth.password | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}
---
{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: nef-grafana-secret
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: grafana
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: helm
type: Opaque
data:
  # Grafana admin credentials
  # Generate secure admin password with: openssl rand -base64 32
  admin-user: {{ .Values.grafana.auth.adminUser | default "admin" | b64enc | quote }}
  admin-password: {{ .Values.grafana.auth.adminPassword | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}
